export default {
  ui: {
    home: 'Start',
    hubTitle: 'Barcelona nach Vierteln',
    hubMetaTitle: 'Barcelonas Viertel: Stadtspaziergänge auf eigene Faust in 13 Bezirken',
    hubLede: 'Dreizehn Bezirke, jeder mit eigenem Charakter. Wie sich jeder zu Fuß anfühlt, einige der Stationen, zu denen unsere Quests führen, und die vollständige Liste der Touren.',
    hubMeta: 'Selbstgeführte Spaziergänge durch 13 Viertel Barcelonas – Gotisches Viertel, El Born, Raval, Eixample, Gràcia, Montjuïc und mehr. Wie jeder Bezirk ist und wohin die Quests führen.',
    pageTitle: (d) => `${d}, Barcelona: selbstgeführte Stadtspaziergänge`,
    metaDesc: (d, n, s) => `${d} zu Fuß: ${n} selbstgeführte Quests, ${s} Stationen. Wie das Viertel ist, einige Orte, die den Weg lohnen, und alle Routen im Überblick.`,
    stopsHeading: 'Ein paar Stationen, die den Weg lohnen',
    stopsNote: 'Nur eine kleine Auswahl. In der App schaltet sich jede Station frei, wenn du dort ankommst – mit einem Detail, das die meisten Besucher übersehen.',
    questsHeading: (d) => `Quests in ${d}`,
    stopsN: (n) => `${n} Stationen`,
    freeTag: 'Gratis',
    inQuest: 'Aus der Quest',
    ctaTitle: 'Mit der App erlaufen',
    ctaText: 'Quest wählen, dem Kompass folgen, an jeder Station einchecken. Kein Konto zum Start, keine Werbung, kein Abo.',
    appStore: 'Bald im App Store',
    allDistricts: 'Alle Bezirke',
    otherDistricts: 'Weitere Bezirke',
    homeSectionTitle: 'Nach Vierteln entdecken',
    homeSectionLede: 'Wie sich jeder Bezirk zu Fuß anfühlt und wohin die Quests führen.',
    questsCount: (n) => `${n} Quests`,
  },
  intros: {
    'gothic-quarter': 'Das Gotische Viertel ist der älteste Teil Barcelonas: Unter seinen Straßen liegt die römische Kolonie Barcino, und die mittelalterliche Stadt wurde darauf gebaut. Heute ist es ein Gewirr enger Gassen zwischen der Kathedrale, der Plaça de Sant Jaume und der Plaça Reial. Die meisten Besucher durchqueren es auf dem Weg woandershin. Die Quests hier bremsen dich: römische Säulen in einem Innenhof, das verlorene jüdische Viertel, Tavernen, die seit hundert Jahren ausschenken, und Ecken, die in der Abenddämmerung am schönsten sind.',
    'el-born': 'El Born – offiziell Sant Pere, Santa Caterina i la Ribera – war das Viertel der mittelalterlichen Kaufleute. Der Carrer de Montcada ist eine Reihe gotischer Paläste, von denen mehrere heute Museen sind, und mittendrin steht Santa Maria del Mar. Ringsum liegen der Palau de la Música, der Markt Santa Caterina mit seinem Wellendach und der Parc de la Ciutadella. Dieselben engen Gassen gehören zu den besten der Stadt für Tapas und Cocktails.',
    'el-raval': 'El Raval wuchs außerhalb der mittelalterlichen Mauer als Hinterhof der Stadt: zuerst Klöster, Spitäler und Werkstätten, später überfüllte Arbeiterhäuser. Bis heute ist es der gemischteste und am wenigsten polierte Teil der Altstadt – ein romanisches Kloster ein paar Straßen von der weißen Fassade des MACBA, historische Bohème-Bars neben pakistanischen Lebensmittelläden, die Boqueria an seinem Rand. Die Quests trennen den Raval, den man sehen sollte, von dem, durch den man nur hindurchgeht.',
    'barceloneta': 'Die Barceloneta wurde im 18. Jahrhundert als Raster schmaler Häuserblocks für Familien angelegt, die dem Bau der Festung Ciutadella weichen mussten. Sie wurde zum Viertel der Fischer und Hafenarbeiter, und so isst man hier noch heute: Bombas, Wermut und Reisgerichte am Meer. Über den Strand hinaus führen die Quests durch den alten Hafen, zum Fischerkai, an die olympische Uferfront von 1992 und zur Seilbahn über dem Hafen.',
    'eixample': 'Das Eixample ist Ildefons Cerdàs Rasterstadt aus dem 19. Jahrhundert: quadratische Blocks mit abgeschrägten Ecken, die Licht und Luft hereinlassen. Das Bürgertum füllte es mit Modernisme-Häusern: Casa Batlló, La Pedrera, Sagrada Família und die Werke von Gaudís Rivalen Domènech i Montaner und Puig i Cadafalch. Die Quests gehen über die berühmten Fassaden hinaus: Gärten im Inneren der Blocks, private Passagen, Barcelonas Chinatown und die Bars alter Schule.',
    'gracia': 'Gràcia war bis 1897 eine eigenständige Stadt und fühlt sich noch immer so an: niedrige Häuser, kleine Plätze und ein ausgeprägtes lokales Selbstbewusstsein. Die Quests folgen seiner Geschichte von Platz zu Platz – Plaça de la Vila, Plaça del Diamant, Plaça del Sol – und steigen hinauf zu Gaudís erstem Haus, der Casa Vicens, und zum Park Güell. Abends füllt sich Gràcia: Wermut-Bodegas, Gin-Bars, Jazz und Jam-Sessions.',
    'sants-montjuic': 'Sants-Montjuïc verbindet zwei sehr verschiedene Welten. Der Montjuïc wurde für die Weltausstellung 1929 herausgeputzt und noch einmal für die Olympischen Spiele 1992: die Font Màgica, der Palau Nacional, die Burg und Gärten mit Blick auf den Hafen. Unterhalb liegen Sants und Poble-sec, Arbeiterviertel rund um alte Textilfabriken – heute Parks, Kulturzentren und einige der lebhaftesten Tapas-Straßen der Stadt.',
    'sant-marti': 'Zu Sant Martí gehört Poblenou, einst wegen seiner Fabriken und Schornsteine das katalanische Manchester genannt. Viele dieser Fabriken sind heute Lofts, Museen und Designstudios, während die Torre Glòries und der neue Glòries-Park für das jüngste Gesicht der Stadt stehen. Am Meer reiht sich Strand an Strand – Bogatell, Mar Bella, Llevant –, angelegt im Vorfeld der Spiele von 1992, und nachts werden die alten Lagerhallen zu Clubs.',
    'sarria-sant-gervasi': 'Sarrià-Sant Gervasi ist Barcelonas Oberstadt: ehemalige Dörfer und Sommersitze, die zu den Collserola-Hügeln hinaufsteigen. Sarrià war bis 1921 eine eigene Gemeinde und hat seinen Dorfplatz und seinen Markt bewahrt. Hier oben findet man den weniger bekannten Gaudí – Bellesguard und das Teresianes-Kolleg –, Modernisme-Villen, ruhige Gärten und ganz oben den Tibidabo mit seiner Kirche über der ganzen Stadt.',
    'les-corts': 'Les Corts war bis Ende des 19. Jahrhunderts ein eigenes Dorf und ist heute vor allem für das Camp Nou des FC Barcelona bekannt. Die Quests zeigen eine andere Seite: Gaudís schmiedeeisernes Drachentor am Güell-Anwesen, die Gärten des Königspalastes von Pedralbes und das gotische Kloster darüber, das alte Bauernhaus, in dem Barças Nachwuchsakademie groß wurde, und die ruhigen Plätze dessen, was vom Dorf übrig ist.',
    'horta-guinardo': 'Horta-Guinardó zieht sich die Hügel nördlich des Zentrums hinauf. Das alte Horta war ein Dorf aus Bauernhöfen und Brunnen, und ganz in der Nähe liegt der Laberint d’Horta, der älteste Garten der Stadt, mit seinem Zypressenlabyrinth. Guinardó hat das Modernisme-Ensemble Sant Pau und Parks am Hang, dazu den Turó de la Rovira – eine Flakstellung aus dem Bürgerkrieg, bekannt als „die Bunker“, mit einem der besten Rundumblicke über Barcelona.',
    'sant-andreu': 'Sant Andreu de Palomar war bis 1897 eine eigene Stadt, und sein alter Kern hat noch immer eine Hauptstraße, einen Markt und eine große Pfarrkirche. Im 19. Jahrhundert kam die Industrie: Die Garnfabrik Fabra i Coats ist heute ein Kulturzentrum, und die Casa Bloc, ein Wohnblock aus den 1930er-Jahren, ist ein Meilenstein der modernen Architektur in Barcelona. Samstags geht das ganze Viertel zum Wermut.',
    'nou-barris': 'Nou Barris ist das Barcelona, das kaum ein Besucher sieht: ein Bezirk, der in den 1950er- bis 70er-Jahren schnell an den Hängen der Collserola hochgezogen wurde und in dem die Anwohner um jeden Park und jede Schule kämpften. Doch er ist älter als seine Wohntürme – Bauernhöfe, eine Dorfkirche, eine psychiatrische Klinik aus dem 19. Jahrhundert, heute Sitz der Bezirksverwaltung, und am Stadtrand die unvollendete Burg Torre Baró mit Blick über ganz Barcelona.',
  },
};
