export default {
  ui: {
    home: 'Home',
    hubTitle: 'Barcelona by neighbourhood',
    hubMetaTitle: 'Barcelona neighbourhoods: self-guided walking quests in 13 districts',
    hubLede: 'Thirteen districts, each with its own character. Here is what each one is like on foot, a few of the stops our quests lead to, and the full list of walks.',
    hubMeta: 'Self-guided walks through 13 Barcelona neighbourhoods — Gothic Quarter, El Born, Raval, Eixample, Gràcia, Montjuïc and more. What each district is like and where the quests lead.',
    pageTitle: (d) => `${d}, Barcelona: self-guided walking quests`,
    metaDesc: (d, n, s) => `${d} on foot: ${n} self-guided walking quests, ${s} stops. What the neighbourhood is like, a few places worth the walk, and the full list of routes.`,
    stopsHeading: 'A few stops worth the walk',
    stopsNote: 'A small sample. In the app, each stop unlocks when you reach it — with a detail most visitors miss.',
    questsHeading: (d) => `Walking quests in ${d}`,
    stopsN: (n) => `${n} stops`,
    freeTag: 'Free',
    inQuest: 'From the quest',
    ctaTitle: 'Walk it with the app',
    ctaText: 'Pick a quest, follow the compass, check in at each stop. No account needed to start, no ads, no subscription.',
    appStore: 'Coming to the App Store',
    allDistricts: 'All districts',
    otherDistricts: 'Other districts',
    homeSectionTitle: 'Explore by neighbourhood',
    homeSectionLede: 'What each district is like on foot, and where the quests go.',
    questsCount: (n) => `${n} quests`,
  },
  intros: {
    'gothic-quarter': 'The Gothic Quarter is the oldest part of Barcelona: the Roman colony of Barcino lies beneath its streets, and the medieval city was built on top of it. Today it is a tangle of narrow lanes between the Cathedral, Plaça de Sant Jaume and Plaça Reial. Most visitors cross it on the way to somewhere else. The quests here slow you down — Roman columns hidden in a courtyard, the lost Jewish quarter, taverns that have been pouring for a century, and the corners that look best at dusk.',
    'el-born': 'El Born — officially Sant Pere, Santa Caterina i la Ribera — was the medieval merchants’ quarter. Carrer de Montcada is a row of Gothic palaces, several of them museums today, and Santa Maria del Mar stands at the heart of it all. Around it are the Palau de la Música, the Santa Caterina market with its wavy roof and the Parc de la Ciutadella. The same narrow streets are some of the best in the city for tapas and cocktails.',
    'el-raval': 'El Raval grew outside the medieval wall as the city’s backyard: convents, hospitals and workshops first, crowded tenements later. It is still the most mixed and least polished part of the old town — a Romanesque monastery a few streets from MACBA’s white façade, historic bohemian bars next to Pakistani grocers, the Boqueria on its edge. The quests here separate the Raval worth seeing from the Raval you simply walk through.',
    'barceloneta': 'Barceloneta was laid out in the 18th century as a grid of narrow blocks for families displaced when the Ciutadella fortress was built. It became the quarter of fishermen and dockworkers, and it still eats like one: bombas, vermouth and rice by the sea. Beyond the beach itself, the quests cover the old port, the fishing wharf, the 1992 Olympic waterfront and the cable car over the harbour.',
    'eixample': 'The Eixample is Ildefons Cerdà’s 19th-century grid — square blocks with cut corners that let in light and air. The bourgeoisie filled it with Modernista houses: Casa Batlló, La Pedrera, the Sagrada Família, and the work of Gaudí’s rivals Domènech i Montaner and Puig i Cadafalch. The quests go beyond the famous façades: gardens hidden inside the blocks, private passages, Barcelona’s Chinatown and the old-school bars of the grid.',
    'gracia': 'Gràcia was an independent town until 1897, and it still feels like one: low buildings, small squares and a strong local identity. The quests follow its history through the squares — Plaça de la Vila, Plaça del Diamant, Plaça del Sol — and climb to Gaudí’s first house, Casa Vicens, and to Park Güell. In the evening Gràcia fills up: vermouth bodegas, gin bars, jazz and jam sessions.',
    'sants-montjuic': 'Sants-Montjuïc joins two very different worlds. Montjuïc hill was dressed up for the 1929 International Exhibition and again for the 1992 Olympics: the Magic Fountain, the Palau Nacional, the castle, and gardens with views over the port. Below it, Sants and Poble-sec are working neighbourhoods built around old textile mills — now parks, cultural centres and some of the liveliest tapas streets in the city.',
    'sant-marti': 'Sant Martí takes in Poblenou, once called the Catalan Manchester for its factories and chimneys. Many of those factories are now lofts, museums and design studios, while the Torre Glòries and the new Glòries park mark the city’s newest face. Along the sea runs a string of beaches — Bogatell, Mar Bella, Llevant — opened in the run-up to the 1992 Olympics, and at night the old warehouses turn into clubs.',
    'sarria-sant-gervasi': 'Sarrià-Sant Gervasi is Barcelona’s uptown: former villages and summer estates climbing towards the Collserola hills. Sarrià itself was a separate town until 1921 and still keeps its village square and market. Up here you find the lesser-known Gaudí — Bellesguard and the Teresianes school — Modernista villas, quiet gardens and, at the very top, Tibidabo with its church looking over the whole city.',
    'les-corts': 'Les Corts was a village of its own until the late 19th century, and today it is best known for FC Barcelona’s Camp Nou. The quests show another side: Gaudí’s wrought-iron dragon gate at the Güell estate, the royal palace gardens of Pedralbes and the Gothic monastery above them, the old farmhouse where Barça’s youth academy grew up, and the quiet squares of what remains of the village.',
    'horta-guinardo': 'Horta-Guinardó climbs the hills north of the centre. Old Horta was a village of farmhouses and water wells, and nearby is the Laberint d’Horta, the oldest garden in the city, with its cypress maze. Guinardó has the Sant Pau Modernista hospital and hillside parks, and the Turó de la Rovira — a civil-war anti-aircraft battery known as “the bunkers”, with one of the best all-round views of Barcelona.',
    'sant-andreu': 'Sant Andreu de Palomar was a town of its own until 1897, and its old centre still has a main street, a market and a big parish church. Industry came in the 19th century: the Fabra i Coats thread factory is now a cultural centre, and Casa Bloc, a 1930s housing block, is a landmark of modern architecture in Barcelona. On Saturdays the whole neighbourhood goes out for vermouth.',
    'nou-barris': 'Nou Barris is the Barcelona most visitors never see: a district built fast in the 1950s–70s on the slopes of Collserola, where neighbours fought for every park and school. But it is older than its tower blocks — farmhouses, a village church, a 19th-century psychiatric hospital that now houses the district council, and at the city’s edge the unfinished castle of Torre Baró, with a view across all of Barcelona.',
  },
};
