export default {
  ui: {
    home: 'Inicio',
    hubTitle: 'Barcelona por barrios',
    hubMetaTitle: 'Barrios de Barcelona: rutas a pie autoguiadas en 13 distritos',
    hubLede: 'Trece distritos, cada uno con su propio carácter. Cómo es cada uno a pie, algunas de las paradas a las que llevan nuestras rutas y la lista completa de paseos.',
    hubMeta: 'Rutas a pie autoguiadas por 13 barrios de Barcelona: Barrio Gótico, El Born, Raval, Eixample, Gràcia, Montjuïc y más. Cómo es cada distrito y adónde llevan las misiones.',
    pageTitle: (d) => `${d}, Barcelona: rutas a pie autoguiadas`,
    metaDesc: (d, n, s) => `${d} a pie: ${n} rutas autoguiadas con misiones, ${s} paradas. Cómo es el barrio, algunos lugares que merecen el paseo y la lista completa de rutas.`,
    stopsHeading: 'Algunas paradas que merecen el paseo',
    stopsNote: 'Solo una muestra. En la app, cada parada se desbloquea al llegar, con un detalle que la mayoría de visitantes pasa por alto.',
    questsHeading: (d) => `Rutas a pie en ${d}`,
    stopsN: (n) => `${n} paradas`,
    freeTag: 'Gratis',
    inQuest: 'De la ruta',
    ctaTitle: 'Recórrelo con la app',
    ctaText: 'Elige una ruta, sigue la brújula y regístrate en cada parada. Sin cuenta para empezar, sin anuncios, sin suscripción.',
    appStore: 'Próximamente en App Store',
    allDistricts: 'Todos los distritos',
    otherDistricts: 'Otros distritos',
    homeSectionTitle: 'Explora por barrios',
    homeSectionLede: 'Cómo es cada distrito a pie y adónde llevan las rutas.',
    questsCount: (n) => `${n} rutas`,
  },
  intros: {
    'gothic-quarter': 'El Barrio Gótico es la parte más antigua de Barcelona: bajo sus calles está la colonia romana de Barcino, y la ciudad medieval se construyó encima. Hoy es una maraña de callejones entre la Catedral, la Plaça de Sant Jaume y la Plaça Reial. La mayoría de visitantes lo cruza de camino a otra parte. Estas rutas te hacen ir más despacio: columnas romanas escondidas en un patio, el antiguo barrio judío, tabernas que llevan un siglo sirviendo y los rincones que mejor lucen al atardecer.',
    'el-born': 'El Born —oficialmente Sant Pere, Santa Caterina i la Ribera— fue el barrio de los mercaderes medievales. El Carrer de Montcada es una hilera de palacios góticos, varios convertidos hoy en museos, y Santa Maria del Mar se alza en el centro de todo. Alrededor están el Palau de la Música, el mercado de Santa Caterina con su tejado ondulado y el Parc de la Ciutadella. Esas mismas callejuelas están entre las mejores de la ciudad para tapas y cócteles.',
    'el-raval': 'El Raval creció fuera de la muralla medieval como el patio trasero de la ciudad: primero conventos, hospitales y talleres; después, casas obreras abarrotadas. Sigue siendo la parte más mezclada y menos pulida del casco antiguo: un monasterio románico a pocas calles de la fachada blanca del MACBA, bares bohemios históricos junto a colmados paquistaníes y la Boqueria en su borde. Estas rutas separan el Raval que merece la pena ver del Raval que solo se atraviesa.',
    'barceloneta': 'La Barceloneta se trazó en el siglo XVIII como una cuadrícula de manzanas estrechas para las familias desplazadas por la construcción de la fortaleza de la Ciutadella. Se convirtió en el barrio de pescadores y estibadores, y todavía come como tal: bombas, vermut y arroces junto al mar. Más allá de la playa, las rutas recorren el puerto viejo, el muelle de pescadores, el frente marítimo olímpico de 1992 y el teleférico sobre el puerto.',
    'eixample': 'El Eixample es la cuadrícula de Ildefons Cerdà del siglo XIX: manzanas cuadradas con chaflanes que dejan entrar luz y aire. La burguesía la llenó de casas modernistas: la Casa Batlló, La Pedrera, la Sagrada Família y las obras de los rivales de Gaudí, Domènech i Montaner y Puig i Cadafalch. Las rutas van más allá de las fachadas famosas: jardines escondidos dentro de las manzanas, pasajes privados, el barrio chino de Barcelona y los bares de toda la vida.',
    'gracia': 'Gràcia fue un municipio independiente hasta 1897, y todavía lo parece: edificios bajos, plazas pequeñas y una identidad local muy marcada. Las rutas siguen su historia de plaza en plaza —Plaça de la Vila, Plaça del Diamant, Plaça del Sol— y suben hasta la primera casa de Gaudí, la Casa Vicens, y el Park Güell. Por la noche Gràcia se llena: bodegas de vermut, bares de gin, jazz y jam sessions.',
    'sants-montjuic': 'Sants-Montjuïc une dos mundos muy distintos. La montaña de Montjuïc se engalanó para la Exposición Internacional de 1929 y de nuevo para los Juegos Olímpicos de 1992: la Font Màgica, el Palau Nacional, el castillo y jardines con vistas al puerto. A sus pies, Sants y el Poble-sec son barrios obreros crecidos alrededor de antiguas fábricas textiles, hoy parques, centros culturales y algunas de las calles de tapas más animadas de la ciudad.',
    'sant-marti': 'Sant Martí incluye el Poblenou, al que llamaron el Manchester catalán por sus fábricas y chimeneas. Muchas de esas fábricas son hoy lofts, museos y estudios de diseño, mientras la Torre Glòries y el nuevo parque de Glòries marcan la cara más nueva de la ciudad. Junto al mar se suceden playas —Bogatell, Mar Bella, Llevant— abiertas en los años previos a los Juegos de 1992, y de noche las viejas naves se convierten en discotecas.',
    'sarria-sant-gervasi': 'Sarrià-Sant Gervasi es la parte alta de Barcelona: antiguos pueblos y fincas de veraneo que suben hacia Collserola. Sarrià fue un municipio aparte hasta 1921 y conserva su plaza de pueblo y su mercado. Aquí arriba está el Gaudí menos conocido —Bellesguard y el colegio de las Teresianas—, villas modernistas, jardines tranquilos y, en lo más alto, el Tibidabo con su templo mirando a toda la ciudad.',
    'les-corts': 'Les Corts fue un pueblo propio hasta finales del siglo XIX y hoy se le conoce sobre todo por el Camp Nou del FC Barcelona. Las rutas enseñan otra cara: la puerta del dragón de hierro forjado de Gaudí en la finca Güell, los jardines del palacio real de Pedralbes y el monasterio gótico sobre ellos, la vieja masía donde creció la cantera del Barça y las plazas tranquilas de lo que queda del pueblo.',
    'horta-guinardo': 'Horta-Guinardó sube por las colinas al norte del centro. La vieja Horta era un pueblo de masías y pozos, y muy cerca está el Laberint d’Horta, el jardín más antiguo de la ciudad, con su laberinto de cipreses. El Guinardó tiene el recinto modernista de Sant Pau y parques en ladera, y el Turó de la Rovira, una batería antiaérea de la Guerra Civil conocida como «los búnkeres», con una de las mejores vistas panorámicas de Barcelona.',
    'sant-andreu': 'Sant Andreu de Palomar fue un municipio propio hasta 1897, y su centro antiguo conserva la calle mayor, el mercado y una gran iglesia parroquial. La industria llegó en el siglo XIX: la fábrica de hilos Fabra i Coats es hoy un centro cultural, y la Casa Bloc, un bloque de viviendas de los años treinta, es un hito de la arquitectura moderna en Barcelona. Los sábados, todo el barrio sale a hacer el vermut.',
    'nou-barris': 'Nou Barris es la Barcelona que casi ningún visitante ve: un distrito levantado deprisa entre los años cincuenta y setenta en las laderas de Collserola, donde los vecinos lucharon por cada parque y cada escuela. Pero es más antiguo que sus bloques: masías, una iglesia de pueblo, un hospital psiquiátrico del siglo XIX que hoy acoge la sede del distrito y, en el límite de la ciudad, el castillo inacabado de Torre Baró, con vistas a toda Barcelona.',
  },
};
