export default {
  ui: {
    home: 'Accueil',
    hubTitle: 'Barcelone quartier par quartier',
    hubMetaTitle: 'Quartiers de Barcelone : balades à pied autoguidées dans 13 districts',
    hubLede: 'Treize districts, chacun avec son caractère. À quoi ressemble chacun à pied, quelques-uns des arrêts où mènent nos quêtes, et la liste complète des balades.',
    hubMeta: 'Balades autoguidées dans 13 quartiers de Barcelone : quartier gothique, El Born, Raval, Eixample, Gràcia, Montjuïc et plus. À quoi ressemble chaque district et où mènent les quêtes.',
    pageTitle: (d) => `${d}, Barcelone : balades à pied autoguidées`,
    metaDesc: (d, n, s) => `${d} à pied : ${n} quêtes autoguidées, ${s} arrêts. À quoi ressemble le quartier, quelques lieux qui valent la marche et la liste complète des parcours.`,
    stopsHeading: 'Quelques arrêts qui valent la marche',
    stopsNote: 'Un petit échantillon. Dans l’app, chaque arrêt se débloque quand vous y arrivez, avec un détail que la plupart des visiteurs manquent.',
    questsHeading: (d) => `Quêtes à pied : ${d}`,
    stopsN: (n) => `${n} arrêts`,
    freeTag: 'Gratuit',
    inQuest: 'Dans la quête',
    ctaTitle: 'À faire avec l’app',
    ctaText: 'Choisissez une quête, suivez la boussole, validez chaque arrêt. Pas de compte pour commencer, pas de pub, pas d’abonnement.',
    appStore: 'Bientôt sur l’App Store',
    allDistricts: 'Tous les districts',
    otherDistricts: 'Autres districts',
    homeSectionTitle: 'Explorer par quartier',
    homeSectionLede: 'À quoi ressemble chaque district à pied, et où mènent les quêtes.',
    questsCount: (n) => `${n} quêtes`,
  },
  intros: {
    'gothic-quarter': 'Le quartier gothique est la partie la plus ancienne de Barcelone : la colonie romaine de Barcino repose sous ses rues, et la ville médiévale s’est construite par-dessus. C’est aujourd’hui un lacis de ruelles entre la cathédrale, la Plaça de Sant Jaume et la Plaça Reial. La plupart des visiteurs le traversent en allant ailleurs. Ces quêtes vous font ralentir : des colonnes romaines cachées dans une cour, l’ancien quartier juif, des tavernes qui servent depuis un siècle et les coins les plus beaux au crépuscule.',
    'el-born': 'El Born — officiellement Sant Pere, Santa Caterina i la Ribera — était le quartier des marchands au Moyen Âge. Le Carrer de Montcada aligne des palais gothiques, dont plusieurs abritent aujourd’hui des musées, et Santa Maria del Mar se dresse au cœur de tout. Autour : le Palau de la Música, le marché de Santa Caterina et son toit ondulé, le Parc de la Ciutadella. Ces mêmes ruelles comptent parmi les meilleures de la ville pour les tapas et les cocktails.',
    'el-raval': 'Le Raval a grandi hors de l’enceinte médiévale comme l’arrière-cour de la ville : couvents, hôpitaux et ateliers d’abord, immeubles ouvriers surpeuplés ensuite. C’est encore la partie la plus mélangée et la moins lissée de la vieille ville : un monastère roman à quelques rues de la façade blanche du MACBA, des bars bohèmes historiques à côté d’épiceries pakistanaises, la Boqueria à sa lisière. Ces quêtes distinguent le Raval qui vaut le détour de celui qu’on se contente de traverser.',
    'barceloneta': 'La Barceloneta a été tracée au XVIIIe siècle en damier de blocs étroits pour les familles chassées par la construction de la forteresse de la Ciutadella. Elle est devenue le quartier des pêcheurs et des dockers, et on y mange toujours comme eux : bombas, vermouth et riz face à la mer. Au-delà de la plage, les quêtes parcourent le vieux port, le quai des pêcheurs, le front de mer olympique de 1992 et le téléphérique au-dessus du port.',
    'eixample': 'L’Eixample, c’est le quadrillage d’Ildefons Cerdà au XIXe siècle : des îlots carrés aux angles coupés qui laissent entrer la lumière et l’air. La bourgeoisie l’a rempli de maisons modernistes : la Casa Batlló, La Pedrera, la Sagrada Família et les œuvres des rivaux de Gaudí, Domènech i Montaner et Puig i Cadafalch. Les quêtes vont au-delà des façades célèbres : jardins cachés au cœur des îlots, passages privés, le quartier chinois de Barcelone et les bars à l’ancienne.',
    'gracia': 'Gràcia était une ville indépendante jusqu’en 1897, et elle en a gardé l’allure : immeubles bas, petites places et forte identité locale. Les quêtes suivent son histoire de place en place — Plaça de la Vila, Plaça del Diamant, Plaça del Sol — et montent jusqu’à la première maison de Gaudí, la Casa Vicens, et au Park Güell. Le soir, Gràcia se remplit : bodegas à vermouth, bars à gin, jazz et jam sessions.',
    'sants-montjuic': 'Sants-Montjuïc réunit deux mondes très différents. La colline de Montjuïc s’est parée pour l’Exposition internationale de 1929, puis pour les Jeux olympiques de 1992 : la Font Màgica, le Palau Nacional, le château et des jardins avec vue sur le port. À ses pieds, Sants et Poble-sec sont des quartiers ouvriers nés autour d’anciennes filatures, devenues parcs, centres culturels et quelques-unes des rues à tapas les plus animées de la ville.',
    'sant-marti': 'Sant Martí englobe Poblenou, jadis surnommé le Manchester catalan pour ses usines et ses cheminées. Beaucoup de ces usines sont devenues lofts, musées et studios de design, tandis que la Torre Glòries et le nouveau parc des Glòries incarnent le visage le plus récent de la ville. Le long de la mer s’enchaînent des plages — Bogatell, Mar Bella, Llevant — ouvertes à l’approche des Jeux de 1992, et la nuit, les anciens entrepôts deviennent des clubs.',
    'sarria-sant-gervasi': 'Sarrià-Sant Gervasi, c’est le haut de Barcelone : anciens villages et domaines d’été qui grimpent vers les collines de Collserola. Sarrià fut une commune à part jusqu’en 1921 et garde sa place de village et son marché. Là-haut se trouve le Gaudí méconnu — Bellesguard et le collège des Thérésiennes —, des villas modernistes, des jardins calmes et, tout au sommet, le Tibidabo et son église qui domine la ville.',
    'les-corts': 'Les Corts était un village à part entière jusqu’à la fin du XIXe siècle ; on le connaît surtout aujourd’hui pour le Camp Nou du FC Barcelone. Les quêtes en montrent une autre face : la porte au dragon en fer forgé de Gaudí au domaine Güell, les jardins du palais royal de Pedralbes et le monastère gothique qui les surplombe, la vieille ferme où a grandi le centre de formation du Barça, et les places tranquilles de ce qui reste du village.',
    'horta-guinardo': 'Horta-Guinardó escalade les collines au nord du centre. Le vieil Horta était un village de fermes et de puits ; tout près se trouve le Laberint d’Horta, le plus ancien jardin de la ville, avec son labyrinthe de cyprès. Le Guinardó abrite l’ensemble moderniste de Sant Pau et des parcs à flanc de colline, ainsi que le Turó de la Rovira, une batterie antiaérienne de la guerre civile surnommée « les bunkers », avec l’une des plus belles vues panoramiques sur Barcelone.',
    'sant-andreu': 'Sant Andreu de Palomar était une commune indépendante jusqu’en 1897, et son vieux centre garde sa grand-rue, son marché et une grande église paroissiale. L’industrie est arrivée au XIXe siècle : la filature Fabra i Coats est aujourd’hui un centre culturel, et la Casa Bloc, un immeuble de logements des années 1930, est un jalon de l’architecture moderne à Barcelone. Le samedi, tout le quartier sort pour le vermouth.',
    'nou-barris': 'Nou Barris, c’est la Barcelone que presque aucun visiteur ne voit : un district bâti à la hâte entre les années 1950 et 1970 sur les pentes de Collserola, où les habitants se sont battus pour chaque parc et chaque école. Mais il est plus ancien que ses tours : des fermes, une église de village, un hôpital psychiatrique du XIXe siècle qui abrite aujourd’hui la mairie du district et, aux confins de la ville, le château inachevé de Torre Baró, avec vue sur tout Barcelone.',
  },
};
