export default {
  ui: {
    home: 'Home',
    hubTitle: 'Barcellona quartiere per quartiere',
    hubMetaTitle: 'Quartieri di Barcellona: passeggiate autoguidate in 13 distretti',
    hubLede: 'Tredici distretti, ognuno con il suo carattere. Com’è ciascuno a piedi, alcune delle tappe a cui portano le nostre quest e l’elenco completo delle passeggiate.',
    hubMeta: 'Passeggiate autoguidate in 13 quartieri di Barcellona: Quartiere Gotico, El Born, Raval, Eixample, Gràcia, Montjuïc e altri. Com’è ogni distretto e dove portano le quest.',
    pageTitle: (d) => `${d}, Barcellona: passeggiate autoguidate`,
    metaDesc: (d, n, s) => `${d} a piedi: ${n} quest autoguidate, ${s} tappe. Com’è il quartiere, alcuni luoghi che valgono la camminata e l’elenco completo dei percorsi.`,
    stopsHeading: 'Alcune tappe che valgono la camminata',
    stopsNote: 'Solo un assaggio. Nell’app ogni tappa si sblocca quando ci arrivi, con un dettaglio che la maggior parte dei visitatori non nota.',
    questsHeading: (d) => `Quest a piedi: ${d}`,
    stopsN: (n) => `${n} tappe`,
    freeTag: 'Gratis',
    inQuest: 'Dalla quest',
    ctaTitle: 'Percorrilo con l’app',
    ctaText: 'Scegli una quest, segui la bussola, fai check-in a ogni tappa. Nessun account per iniziare, niente pubblicità, nessun abbonamento.',
    appStore: 'Presto su App Store',
    allDistricts: 'Tutti i distretti',
    otherDistricts: 'Altri distretti',
    homeSectionTitle: 'Esplora per quartiere',
    homeSectionLede: 'Com’è ogni distretto a piedi e dove portano le quest.',
    questsCount: (n) => `${n} quest`,
  },
  intros: {
    'gothic-quarter': 'Il Quartiere Gotico è la parte più antica di Barcellona: sotto le sue strade c’è la colonia romana di Barcino, e la città medievale è stata costruita sopra. Oggi è un intrico di vicoli tra la Cattedrale, Plaça de Sant Jaume e Plaça Reial. La maggior parte dei visitatori lo attraversa diretta altrove. Queste quest ti fanno rallentare: colonne romane nascoste in un cortile, l’antico quartiere ebraico, taverne che servono da un secolo e gli angoli più belli al tramonto.',
    'el-born': 'El Born — ufficialmente Sant Pere, Santa Caterina i la Ribera — era il quartiere dei mercanti medievali. Carrer de Montcada è una fila di palazzi gotici, molti oggi musei, e Santa Maria del Mar sta al centro di tutto. Intorno ci sono il Palau de la Música, il mercato di Santa Caterina con il suo tetto ondulato e il Parc de la Ciutadella. Gli stessi vicoli sono tra i migliori della città per tapas e cocktail.',
    'el-raval': 'Il Raval è cresciuto fuori dalle mura medievali come il cortile sul retro della città: prima conventi, ospedali e botteghe, poi case operaie sovraffollate. È ancora la parte più mescolata e meno levigata della città vecchia: un monastero romanico a poche strade dalla facciata bianca del MACBA, storici bar bohémien accanto a drogherie pakistane, la Boqueria al suo margine. Queste quest separano il Raval che vale la pena vedere da quello che si attraversa e basta.',
    'barceloneta': 'La Barceloneta fu tracciata nel XVIII secolo come una griglia di isolati stretti per le famiglie sfollate dalla costruzione della fortezza della Ciutadella. Divenne il quartiere di pescatori e portuali, e mangia ancora come loro: bombas, vermut e riso sul mare. Oltre alla spiaggia, le quest percorrono il porto vecchio, il molo dei pescatori, il lungomare olimpico del 1992 e la funivia sopra il porto.',
    'eixample': 'L’Eixample è la griglia ottocentesca di Ildefons Cerdà: isolati quadrati con gli angoli smussati che lasciano entrare luce e aria. La borghesia la riempì di case moderniste: Casa Batlló, La Pedrera, la Sagrada Família e le opere dei rivali di Gaudí, Domènech i Montaner e Puig i Cadafalch. Le quest vanno oltre le facciate famose: giardini nascosti dentro gli isolati, passaggi privati, la Chinatown di Barcellona e i bar di una volta.',
    'gracia': 'Gràcia è stata un comune indipendente fino al 1897, e lo sembra ancora: edifici bassi, piazzette e una forte identità locale. Le quest seguono la sua storia di piazza in piazza — Plaça de la Vila, Plaça del Diamant, Plaça del Sol — e salgono fino alla prima casa di Gaudí, Casa Vicens, e al Park Güell. La sera Gràcia si riempie: bodegas di vermut, gin bar, jazz e jam session.',
    'sants-montjuic': 'Sants-Montjuïc unisce due mondi molto diversi. La collina di Montjuïc si è fatta bella per l’Esposizione Internazionale del 1929 e di nuovo per le Olimpiadi del 1992: la Font Màgica, il Palau Nacional, il castello e giardini con vista sul porto. Ai suoi piedi, Sants e Poble-sec sono quartieri operai nati intorno a vecchie fabbriche tessili, oggi parchi, centri culturali e alcune delle vie di tapas più vivaci della città.',
    'sant-marti': 'Sant Martí comprende il Poblenou, un tempo chiamato la Manchester catalana per le sue fabbriche e ciminiere. Molte di quelle fabbriche sono oggi loft, musei e studi di design, mentre la Torre Glòries e il nuovo parco delle Glòries segnano il volto più recente della città. Lungo il mare si susseguono spiagge — Bogatell, Mar Bella, Llevant — aperte in vista delle Olimpiadi del 1992, e di notte i vecchi capannoni diventano club.',
    'sarria-sant-gervasi': 'Sarrià-Sant Gervasi è la Barcellona alta: antichi villaggi e tenute estive che salgono verso le colline di Collserola. Sarrià è stata un comune a sé fino al 1921 e conserva la sua piazza di paese e il suo mercato. Quassù si trova il Gaudí meno noto — Bellesguard e il collegio delle Teresiane —, ville moderniste, giardini tranquilli e, in cima, il Tibidabo con la sua chiesa che guarda tutta la città.',
    'les-corts': 'Les Corts è stato un villaggio a sé fino alla fine dell’Ottocento, e oggi è noto soprattutto per il Camp Nou dell’FC Barcelona. Le quest ne mostrano un altro volto: il cancello del drago in ferro battuto di Gaudí alla tenuta Güell, i giardini del palazzo reale di Pedralbes e il monastero gotico sopra di essi, la vecchia masseria dove è cresciuto il vivaio del Barça e le piazze tranquille di ciò che resta del villaggio.',
    'horta-guinardo': 'Horta-Guinardó sale sulle colline a nord del centro. La vecchia Horta era un villaggio di masserie e pozzi, e poco lontano c’è il Laberint d’Horta, il giardino più antico della città, con il suo labirinto di cipressi. Il Guinardó ha il complesso modernista di Sant Pau e parchi in collina, e il Turó de la Rovira: una batteria antiaerea della guerra civile nota come «i bunker», con una delle migliori viste a 360° su Barcellona.',
    'sant-andreu': 'Sant Andreu de Palomar è stato un comune a sé fino al 1897, e il suo centro storico conserva la via principale, il mercato e una grande chiesa parrocchiale. L’industria arrivò nell’Ottocento: la fabbrica di filati Fabra i Coats è oggi un centro culturale, e la Casa Bloc, un complesso residenziale degli anni Trenta, è una pietra miliare dell’architettura moderna a Barcellona. Il sabato tutto il quartiere esce per il vermut.',
    'nou-barris': 'Nou Barris è la Barcellona che quasi nessun visitatore vede: un distretto costruito in fretta tra gli anni Cinquanta e Settanta sulle pendici di Collserola, dove gli abitanti hanno lottato per ogni parco e ogni scuola. Ma è più antico dei suoi palazzoni: masserie, una chiesa di paese, un ospedale psichiatrico ottocentesco che oggi ospita la sede del distretto e, al confine della città, il castello incompiuto di Torre Baró, con vista su tutta Barcellona.',
  },
};
