const pf = (n, one, few, many) => `${n} ${n === 1 ? one : (n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14)) ? few : many}`;
export default {
  ui: {
    home: 'Strona główna',
    hubTitle: 'Barcelona dzielnica po dzielnicy',
    hubMetaTitle: 'Dzielnice Barcelony: samodzielne spacery z questami w 13 dzielnicach',
    hubLede: 'Trzynaście dzielnic, każda z własnym charakterem. Jaka jest każda z nich na piechotę, kilka przystanków, do których prowadzą nasze questy, i pełna lista spacerów.',
    hubMeta: 'Samodzielne spacery po 13 dzielnicach Barcelony: Dzielnica Gotycka, El Born, Raval, Eixample, Gràcia, Montjuïc i inne. Jaka jest każda dzielnica i dokąd prowadzą questy.',
    pageTitle: (d) => `${d}, Barcelona: samodzielne spacery z questami`,
    metaDesc: (d, n, s) => `${d} na piechotę: ${pf(n, 'quest', 'questy', 'questów')} do samodzielnego przejścia i ${pf(s, 'przystanek', 'przystanki', 'przystanków')} na trasach. Jaka jest dzielnica, kilka miejsc wartych spaceru i pełna lista tras.`,
    stopsHeading: 'Kilka przystanków wartych spaceru',
    stopsNote: 'To tylko próbka. W aplikacji każdy przystanek odblokowuje się, gdy do niego dotrzesz — ze szczegółem, który większość zwiedzających przeoczy.',
    questsHeading: (d) => `Questy: ${d}`,
    stopsN: (n) => `${n} ${n === 1 ? 'przystanek' : (n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14)) ? 'przystanki' : 'przystanków'}`,
    freeTag: 'Za darmo',
    inQuest: 'Z questu',
    ctaTitle: 'Przejdź to z aplikacją',
    ctaText: 'Wybierz quest, idź za kompasem, melduj się na każdym przystanku. Bez konta na start, bez reklam, bez subskrypcji.',
    appStore: 'Wkrótce w App Store',
    allDistricts: 'Wszystkie dzielnice',
    otherDistricts: 'Inne dzielnice',
    homeSectionTitle: 'Odkrywaj dzielnice',
    homeSectionLede: 'Jaka jest każda dzielnica na piechotę i dokąd prowadzą questy.',
    questsCount: (n) => `${n} ${n === 1 ? 'quest' : (n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14)) ? 'questy' : 'questów'}`,
  },
  intros: {
    'gothic-quarter': 'Dzielnica Gotycka to najstarsza część Barcelony: pod jej ulicami leży rzymska kolonia Barcino, a średniowieczne miasto zbudowano na niej. Dziś to plątanina wąskich uliczek między katedrą, Plaça de Sant Jaume i Plaça Reial. Większość turystów tylko ją przecina w drodze gdzie indziej. Tutejsze questy każą zwolnić: rzymskie kolumny ukryte na dziedzińcu, zaginiona dzielnica żydowska, tawerny, które nalewają od stu lat, i zakątki najpiękniejsze o zmierzchu.',
    'el-born': 'El Born — oficjalnie Sant Pere, Santa Caterina i la Ribera — był średniowieczną dzielnicą kupców. Carrer de Montcada to szereg gotyckich pałaców, z których kilka mieści dziś muzea, a w samym środku stoi Santa Maria del Mar. Wokół są Palau de la Música, targ Santa Caterina z falistym dachem i Parc de la Ciutadella. Te same wąskie uliczki należą do najlepszych w mieście na tapas i koktajle.',
    'el-raval': 'El Raval wyrósł za średniowiecznym murem jako zaplecze miasta: najpierw klasztory, szpitale i warsztaty, później przeludnione kamienice robotnicze. Wciąż jest najbardziej wymieszaną i najmniej wygładzoną częścią starego miasta — romański klasztor kilka ulic od białej fasady MACBA, historyczne bary bohemy obok pakistańskich sklepików, Boqueria na jego skraju. Questy oddzielają Raval wart zobaczenia od Ravalu, przez który się tylko przechodzi.',
    'barceloneta': 'Barcelonetę wytyczono w XVIII wieku jako siatkę wąskich kwartałów dla rodzin wysiedlonych pod budowę twierdzy Ciutadella. Stała się dzielnicą rybaków i dokerów i wciąż je się tu jak oni: bombas, vermut i ryż nad morzem. Poza samą plażą questy prowadzą przez stary port, nabrzeże rybackie, olimpijskie wybrzeże z 1992 roku i kolejkę linową nad portem.',
    'eixample': 'Eixample to XIX-wieczna siatka Ildefonsa Cerdy: kwadratowe kwartały ze ściętymi narożnikami, które wpuszczają światło i powietrze. Mieszczaństwo wypełniło ją modernistycznymi kamienicami: Casa Batlló, La Pedrera, Sagrada Família oraz dzieła rywali Gaudíego, Domènecha i Montanera i Puiga i Cadafalcha. Questy wychodzą poza słynne fasady: ogrody ukryte wewnątrz kwartałów, prywatne pasaże, barcelońskie Chinatown i bary starej daty.',
    'gracia': 'Gràcia była osobnym miastem do 1897 roku i wciąż tak się czuje: niskie domy, małe place i silna lokalna tożsamość. Questy idą za jej historią od placu do placu — Plaça de la Vila, Plaça del Diamant, Plaça del Sol — i wspinają się do pierwszego domu Gaudíego, Casa Vicens, oraz do Parku Güell. Wieczorem Gràcia się zapełnia: bodegi z vermutem, bary z ginem, jazz i jam sessions.',
    'sants-montjuic': 'Sants-Montjuïc łączy dwa bardzo różne światy. Wzgórze Montjuïc wystroiło się na Wystawę Światową w 1929 roku i ponownie na igrzyska olimpijskie w 1992: Font Màgica, Palau Nacional, zamek i ogrody z widokiem na port. U jego stóp Sants i Poble-sec to dzielnice robotnicze wyrosłe wokół dawnych fabryk włókienniczych — dziś parków, centrów kultury i jednych z najżywszych ulic z tapas w mieście.',
    'sant-marti': 'Sant Martí obejmuje Poblenou, nazywane kiedyś katalońskim Manchesterem od fabryk i kominów. Wiele z tych fabryk to dziś lofty, muzea i studia projektowe, a Torre Glòries i nowy park Glòries wyznaczają najnowsze oblicze miasta. Wzdłuż morza ciągną się plaże — Bogatell, Mar Bella, Llevant — otwarte przed igrzyskami w 1992 roku, a nocą stare magazyny zamieniają się w kluby.',
    'sarria-sant-gervasi': 'Sarrià-Sant Gervasi to górna Barcelona: dawne wsie i letnie posiadłości wspinające się ku wzgórzom Collserola. Samo Sarrià było osobną gminą do 1921 roku i zachowało wiejski plac i targ. Tu na górze jest mniej znany Gaudí — Bellesguard i kolegium Teresianek — modernistyczne wille, ciche ogrody, a na samym szczycie Tibidabo z kościołem górującym nad całym miastem.',
    'les-corts': 'Les Corts było osobną wsią do końca XIX wieku, a dziś słynie przede wszystkim z Camp Nou FC Barcelony. Questy pokazują inną stronę: kutą bramę ze smokiem Gaudíego w posiadłości Güell, ogrody pałacu królewskiego Pedralbes i gotycki klasztor nad nimi, stary dom, w którym dorastała akademia Barçy, i ciche place tego, co zostało z wsi.',
    'horta-guinardo': 'Horta-Guinardó wspina się na wzgórza na północ od centrum. Stara Horta była wsią gospodarstw i studni, a tuż obok leży Laberint d’Horta, najstarszy ogród w mieście, z labiryntem cyprysów. Guinardó ma modernistyczny zespół Sant Pau i parki na zboczach, a także Turó de la Rovira — baterię przeciwlotniczą z czasów wojny domowej zwaną „bunkrami”, z jednym z najlepszych panoramicznych widoków na Barcelonę.',
    'sant-andreu': 'Sant Andreu de Palomar było osobnym miastem do 1897 roku, a jego stare centrum wciąż ma główną ulicę, targ i duży kościół parafialny. Przemysł przyszedł w XIX wieku: przędzalnia Fabra i Coats jest dziś centrum kultury, a Casa Bloc, blok mieszkalny z lat 30., to kamień milowy architektury modernistycznej w Barcelonie. W soboty cała dzielnica wychodzi na vermut.',
    'nou-barris': 'Nou Barris to Barcelona, której prawie żaden turysta nie widzi: dzielnica zbudowana w pośpiechu w latach 50.–70. na zboczach Collseroli, gdzie mieszkańcy walczyli o każdy park i każdą szkołę. Ale jest starsza niż jej bloki — gospodarstwa, wiejski kościół, XIX-wieczny szpital psychiatryczny, w którym dziś mieści się siedziba dzielnicy, a na skraju miasta niedokończony zamek Torre Baró z widokiem na całą Barcelonę.',
  },
};
